server:
  port: 8011

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: wjdals12#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: aazitsmtp@gmail.com
    password: zxfvnwttuxsohwnk
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  data:
    redis:
      host: localhost
      port: 6379
    #      password: 1234
    jwt:
      secret: ${JWT_SECRET_KEY}




logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace

