server:
  port: 8011

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}  # 기본값: local

---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/auth?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: wjdals12#
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace



---
spring:
  profiles: prod-docker
  datasource:
    url: jdbc:mysql://db:3306/auth?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis
      port: 6379




