server:
  port: 8011

spring:
  datasource:
    url: jdbc:mysql://db:3306/lostark_toy?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: wjdals12#
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
    jwt:
      secret: ${JWT_SECRET_KEY}

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace





